apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-listing-idealista-scraper
  namespace: real-state-fizgon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-listing-idealista-scraper
  template:
    metadata:
      labels:
        app: property-listing-idealista-scraper
    spec:
      hostname: property-listing-idealista-scraper
      containers:
      - name: property-listing-idealista-scraper
        image: property-listing-idealista-scraper:local
        imagePullPolicy: Never
        volumeMounts:
        - name: app-secrets
          mountPath: /app/secrets.json
          subPath: secrets.json
          readOnly: true
      volumes:
      - name: app-secrets
        secret:
          secretName: property-listing-secrets
          items:
          - key: secrets.json
            path: secrets.json
