apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-image-downloader
  namespace: real-state-fizgon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pending-image-downloader
  template:
    metadata:
      labels:
        app: pending-image-downloader
    spec:
      hostname: pending-image-downloader
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
      - name: pending-image-downloader
        image: pending-image-downloader:local
        imagePullPolicy: Never
        volumeMounts:
        - name: app-secrets
          mountPath: /app/secrets.json
          subPath: secrets.json
          readOnly: true
        - name: images-persistent
          mountPath: /app/output/images
      volumes:
      - name: app-secrets
        secret:
          secretName: pending-image-downloader-secrets
          items:
          - key: secrets.json
            path: secrets.json
      - name: images-persistent
        persistentVolumeClaim:
          claimName: idealista-property-images-pvc

