apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-state-http-ingress
  namespace: real-state-fizgon
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
spec:
  ingressClassName: nginx
  rules:
  - host: rabbitmq.${DNS_REAL_STATE_FIZGON_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  - host: prometheus.${DNS_REAL_STATE_FIZGON_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
  - host: grafana.${DNS_REAL_STATE_FIZGON_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
  - host: notification.${DNS_REAL_STATE_FIZGON_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notification-message-sender
            port:
              number: 9464
