kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: realstate-fizgon
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5001"]
    endpoint = ["http://host.docker.internal:5001"]
