apiVersion: v1
kind: PersistentVolume
metadata:
  name: property-detail-images-pv
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nfsvers=4.1
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_SHARED_FOLDER}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: property-detail-images-pvc
  namespace: real-state-fizgon
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: property-detail-images-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-detail-idealista-scraper
  namespace: real-state-fizgon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-detail-idealista-scraper
  template:
    metadata:
      labels:
        app: property-detail-idealista-scraper
    spec:
      hostname: property-detail-idealista-scraper
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
      - name: property-detail-idealista-scraper
        image: property-detail-idealista-scraper:local
        imagePullPolicy: Never
        volumeMounts:
        - name: app-secrets
          mountPath: /app/secrets.json
          subPath: secrets.json
          readOnly: true
        - name: images-persistent
          mountPath: /app/output/images
      volumes:
      - name: app-secrets
        secret:
          secretName: property-detail-secrets
          items:
          - key: secrets.json
            path: secrets.json
      - name: images-persistent
        persistentVolumeClaim:
          claimName: property-detail-images-pvc
