apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-message-sender
  namespace: real-state-fizgon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-message-sender
  template:
    metadata:
      labels:
        app: notification-message-sender
    spec:
      containers:
      - name: notification-message-sender
        image: notification-message-sender:local
        imagePullPolicy: Never
        ports:
        - containerPort: 9464
          name: metrics
        volumeMounts:
        - name: app-secrets
          mountPath: /app/secrets.json
          subPath: secrets.json
          readOnly: true
      volumes:
      - name: app-secrets
        secret:
          secretName: notification-message-sender-secrets
          items:
          - key: secrets.json
            path: secrets.json
---
apiVersion: v1
kind: Service
metadata:
  name: notification-message-sender
  namespace: real-state-fizgon
  labels:
    app: notification-message-sender
spec:
  selector:
    app: notification-message-sender
  ports:
  - name: metrics
    port: 9464
    targetPort: 9464
